---
apiVersion: v1
kind: Service
metadata:
  name: twitter-stream-connect-service
  namespace: kafka
spec:
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app:  twitter-stream-connect
  sessionAffinity: None
  type: ClusterIP