apiVersion: v1
kind: Secret
metadata:
  name: twitter-stream-connect-secrets
  namespace: kafka
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: ZG9hZG1pbgo=
  SPRING_DATASOURCE_PASSWORD: aW5oNHFkczVxcHJzN2owbgo=
