apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.9.2
  nodeSets:
    - name: default
      count: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: do-block-storage
      config:
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
  http:
    tls:
      selfSignedCertificate:
        disabled: true